# coding=utf-8
"""创建所有基础表格

Revision ID: db26c7d0854
Revises: None
Create Date: 2015-07-29 20:32:37.642432

"""

# revision identifiers, used by Alembic.
revision = 'db26c7d0854'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enum_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('display', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['type_id'], ['enum_values.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alt', sa.Unicode(length=256), nullable=True),
    sa.Column('path', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('omnibus_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('photo_omnibus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['omnibus_template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=64), nullable=False),
    sa.Column('display', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('recommend_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], [u'image.id'], ),
    sa.ForeignKeyConstraint(['recommend_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['enum_values.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('login')
    )
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], [u'users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('date_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['status_id'], ['enum_values.id'], ),
    sa.ForeignKeyConstraint(['user_id'], [u'users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_user_id', sa.Integer(), nullable=True),
    sa.Column('receive_user_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['from_user_id'], [u'users.id'], ),
    sa.ForeignKeyConstraint(['receive_user_id'], [u'users.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['enum_values.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('photo_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photographer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['photographer_id'], [u'users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('photo_collection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photographer_id', sa.Integer(), nullable=True),
    sa.Column('uploader_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['photographer_id'], [u'users.id'], ),
    sa.ForeignKeyConstraint(['uploader_id'], [u'users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=True),
    sa.Column('photographer_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('style', sa.String(length=128), nullable=False),
    sa.Column('location', sa.String(length=128), nullable=False),
    sa.Column('lens_needed', sa.String(length=128), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['photographer_id'], [u'users.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], [u'users.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['enum_values.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_experience',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], [u'request.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['enum_values.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('photo_work',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photo_collection_id', sa.Integer(), nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['photo_collection_id'], [u'photo_collection.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favourite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('photo_work_id', sa.Integer(), nullable=True),
    sa.Column('photo_collection_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['photo_collection_id'], [u'users.id'], ),
    sa.ForeignKeyConstraint(['photo_work_id'], [u'photo_work.id'], ),
    sa.ForeignKeyConstraint(['user_id'], [u'users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('photo_work_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photo_work_id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.id'], ),
    sa.ForeignKeyConstraint(['photo_work_id'], ['photo_work.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('photo_work_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.Column('photo_work_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], [u'image.id'], ),
    sa.ForeignKeyConstraint(['photo_work_id'], [u'photo_work.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('photo_work_omnibus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photo_omnibus_id', sa.Integer(), nullable=False),
    sa.Column('photo_work_id', sa.Integer(), nullable=False),
    sa.Column('work_row', sa.Integer(), nullable=False),
    sa.Column('work_col', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['photo_omnibus_id'], [u'photo_omnibus.id'], ),
    sa.ForeignKeyConstraint(['photo_work_id'], [u'photo_work.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('photo_work_favourite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photo_work_id', sa.Integer(), nullable=False),
    sa.Column('favourite_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['favourite_id'], ['favourite.id'], ),
    sa.ForeignKeyConstraint(['photo_work_id'], ['photo_work.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photo_work_favourite')
    op.drop_table('photo_work_omnibus')
    op.drop_table('photo_work_image')
    op.drop_table('photo_work_comment')
    op.drop_table('order_comment')
    op.drop_table('favourite')
    op.drop_table('photo_work')
    op.drop_table('order')
    op.drop_table('user_experience')
    op.drop_table('roles_users')
    op.drop_table('request')
    op.drop_table('photo_collection')
    op.drop_table('photo_category')
    op.drop_table('message')
    op.drop_table('date_status')
    op.drop_table('comment')
    op.drop_table('users')
    op.drop_table('photo_omnibus')
    op.drop_table('role')
    op.drop_table('payment')
    op.drop_table('omnibus_template')
    op.drop_table('image')
    op.drop_table('enum_values')
    ### end Alembic commands ###
