# coding=utf-8
"""在作品集和作品分类对象中增加名字字段

Revision ID: 33eb76c3c32f
Revises: 4b28ce000424
Create Date: 2015-08-07 22:33:02.259836

"""

# revision identifiers, used by Alembic.
revision = '33eb76c3c32f'
down_revision = '4b28ce000424'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo_category', sa.Column('name', sa.String(length=32), nullable=False))
    op.add_column('photo_collection', sa.Column('name', sa.String(length=32), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photo_collection', 'name')
    op.drop_column('photo_category', 'name')
    ### end Alembic commands ###
