# coding=utf-8
"""删除photo_work_image，直接使用photo_work关联image, 在作品集中增加风格

Revision ID: 20953f584d76
Revises: 33eb76c3c32f
Create Date: 2015-08-10 23:33:45.591592

"""

# revision identifiers, used by Alembic.
revision = '20953f584d76'
down_revision = '33eb76c3c32f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # commands auto generated by Alembic - please adjust! ###
    op.add_column('photo_collection', sa.Column('style_id', sa.Integer(),
                                                nullable=True))
    op.create_foreign_key(u'photo_collection_style_id_fkey', 'photo_collection',
                          'enum_values', ['style_id'], ['id'])
    op.drop_table('photo_work_image')
    op.add_column('photo_work', sa.Column('image_id', sa.Integer(),
                                          nullable=True))
    op.create_foreign_key(u'photo_work_image_id_fkey', 'photo_work', 'image',
                          ['image_id'], ['id'])
    # end Alembic commands ###


def downgrade():
    # commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'photo_work', type_='foreignkey')
    op.drop_column('photo_work', 'image_id')
    op.create_table('photo_work_image', sa.Column('id', sa.INTEGER(),
                                                  nullable=False),
                    sa.Column('image_id', sa.INTEGER(), autoincrement=False,
                              nullable=True),
                    sa.Column('photo_work_id', sa.INTEGER(),
                              autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['image_id'],
                                            [u'image.id'],
                                            name=u'photo_work_image_image_id_fkey'),
                    sa.ForeignKeyConstraint(['photo_work_id'],
                                            [u'photo_work.id'],
                                            name=u'photo_work_image_photo_work_id_fkey'),
                    sa.PrimaryKeyConstraint('id', name=u'photo_work_image_pkey')
                    )
    # end Alembic commands ###
