# coding=utf-8
"""在作品集中增加价格，在作品中增加是否为封面

Revision ID: 26b3cab7ece9
Revises: 20953f584d76
Create Date: 2015-08-17 08:29:15.080201

"""

# revision identifiers, used by Alembic.
revision = '26b3cab7ece9'
down_revision = '20953f584d76'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo_collection', sa.Column('price', sa.Numeric(precision=8, scale=2, decimal_return_scale=2), nullable=True))
    op.add_column('photo_work', sa.Column('is_cover', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photo_work', 'is_cover')
    op.drop_column('photo_collection', 'price')
    ### end Alembic commands ###
