# coding=utf-8
"""删除表photo_category，合并到使用enum_value表来存储照片分类

Revision ID: 31ca7e7a871a
Revises: 26b3cab7ece9
Create Date: 2015-08-17 10:46:41.099529

"""

# revision identifiers, used by Alembic.
revision = '31ca7e7a871a'
down_revision = '26b3cab7ece9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'photo_collection_category_id_fkey', 'photo_collection', type_='foreignkey')
    op.drop_column('photo_collection', 'category_id')
    op.drop_table('photo_category')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photo_category',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('photographer_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['photographer_id'], [u'users.id'], name=u'photo_category_photographer_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'photo_category_pkey')
    )
    op.add_column('photo_collection', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(u'photo_collection_category_id_fkey', 'photo_collection', 'photo_category', ['category_id'], ['id'])
    ### end Alembic commands ###
