# coding=utf-8
"""增加用户所擅长的风格表

Revision ID: 4efe4244247d
Revises: 53d80498947f
Create Date: 2015-08-28 00:04:09.729468

"""

# revision identifiers, used by Alembic.
revision = '4efe4244247d'
down_revision = '53d80498947f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_styles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('style_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['style_id'], ['enum_values.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_styles')
    ### end Alembic commands ###
