"""empty message

Revision ID: 1447b8ddf293
Revises: 253dbf2c5574
Create Date: 2015-09-22 21:51:34.135428

"""

# revision identifiers, used by Alembic.
revision = '1447b8ddf293'
down_revision = '253dbf2c5574'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('photo_collection', 'price',
               existing_type=sa.NUMERIC(precision=8, scale=2),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('photo_collection', 'price',
               existing_type=sa.NUMERIC(precision=8, scale=2),
               nullable=True)
    ### end Alembic commands ###
