# coding=utf-8
"""增加作品集评论表，在拍摄请求中增加备注

Revision ID: 253dbf2c5574
Revises: 49f332be690
Create Date: 2015-09-02 11:44:34.157513

"""

# revision identifiers, used by Alembic.
revision = '253dbf2c5574'
down_revision = '49f332be690'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photo_collection_comment',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('photo_collection_id', sa.Integer(), nullable=False),
                    sa.Column('comment_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['comment_id'], ['comment.id'], ),
                    sa.ForeignKeyConstraint(['photo_collection_id'], ['photo_collection.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.add_column(u'request', sa.Column('remark', sa.String(length=512), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'request', 'remark')
    op.drop_table('photo_collection_comment')
    ### end Alembic commands ###
