# coding=utf-8
"""在拍摄请求表中增加拍摄分类字段并删除字符类型的风格字段

Revision ID: 5924eae17021
Revises: 1447b8ddf293
Create Date: 2015-09-22 22:32:23.657902

"""

# revision identifiers, used by Alembic.
revision = '5924eae17021'
down_revision = '1447b8ddf293'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key("request_category_fk", 'request', 'enum_values', ['category_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('style', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    ### end Alembic commands ###
