# coding=utf-8
"""在拍摄请求表中增加价格和金额

Revision ID: 2b2afe87a97c
Revises: 2b5a3e14bc6d
Create Date: 2015-09-23 21:35:31.758407

"""

# revision identifiers, used by Alembic.
revision = '2b2afe87a97c'
down_revision = '2b5a3e14bc6d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('amount', sa.Numeric(precision=8, scale=2, decimal_return_scale=2), nullable=True))
    op.add_column('request', sa.Column('price', sa.Numeric(precision=8, scale=2, decimal_return_scale=2), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request', 'price')
    op.drop_column('request', 'amount')
    ### end Alembic commands ###
