# coding=utf-8
"""在用户中增加常驻摄影地和是否接受出差

Revision ID: 49e6b3cd7e67
Revises: 2b2afe87a97c
Create Date: 2015-10-28 21:09:36.969394

"""

# revision identifiers, used by Alembic.
revision = '49e6b3cd7e67'
down_revision = '2b2afe87a97c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('accept_travel', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('location_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'enum_values', ['location_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'accept_travel')
    op.drop_column('users', 'location_id')
    ### end Alembic commands ###
