# coding=utf-8
"""将request中的location变为选择项

Revision ID: 399e358e81fb
Revises: 49e6b3cd7e67
Create Date: 2015-10-28 23:06:14.306773

"""

# revision identifiers, used by Alembic.
revision = '399e358e81fb'
down_revision = '49e6b3cd7e67'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('location_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'request', 'enum_values', ['location_id'], ['id'])
    op.drop_column('request', 'location')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('location', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'request', type_='foreignkey')
    op.drop_column('request', 'location_id')
    ### end Alembic commands ###
