# coding=utf-8
"""修改作品集和收藏的表结构，将其联系挪到独立表里面去

Revision ID: 4fc66ef91a3a
Revises: db26c7d0854
Create Date: 2015-07-30 20:17:27.659187

"""

# revision identifiers, used by Alembic.
revision = '4fc66ef91a3a'
down_revision = 'db26c7d0854'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photo_collection_favourite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photo_collection_id', sa.Integer(), nullable=False),
    sa.Column('favourite_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['favourite_id'], ['favourite.id'], ),
    sa.ForeignKeyConstraint(['photo_collection_id'], ['photo_collection.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(u'favourite_photo_collection_id_fkey', 'favourite',
                       type_='foreignkey')
    op.drop_constraint(u'favourite_photo_work_id_fkey', 'favourite',
                       type_='foreignkey')
    op.drop_column(u'favourite', 'photo_work_id')
    op.drop_column(u'favourite', 'photo_collection_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'favourite', sa.Column('photo_collection_id', sa.INTEGER(),
                                          autoincrement=False, nullable=True))
    op.add_column(u'favourite', sa.Column('photo_work_id', sa.INTEGER(),
                                          autoincrement=False, nullable=True))
    op.create_foreign_key(u'favourite_photo_work_id_fkey', 'favourite',
                          'photo_work', ['photo_work_id'], ['id'])
    op.create_foreign_key(u'favourite_photo_collection_id_fkey', 'favourite',
                          'users', ['photo_collection_id'], ['id'])
    op.drop_table('photo_collection_favourite')
    ### end Alembic commands ###
